from django.contrib import admin
from auto_car.models import *

admin.site.register(ServiceUser)
admin.site.register(Car)
admin.site.register(ParkingSpace)
admin.site.register(Bill)
admin.site.register(Income)
admin.site.register(VacancyInfo)
admin.site.register(Vacancy)
admin.site.register(CompanyInfo)
admin.site.register(News)
admin.site.register(FAQ)
admin.site.register(Review)
admin.site.register(Coupon)
admin.site.register(Contact)
admin.site.register(YearHistory)
admin.site.register(Service)
admin.site.register(OrderService)
admin.site.register(Cart)
admin.site.register(Employee)