# Generated by Django 5.2.1 on 2025-05-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_car', '0004_serviceuser_alter_car_owners_alter_review_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_parked',
            field=models.BooleanField(default=False),
        ),
    ]
