# Generated by Django 5.2.1 on 2025-05-13 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_car', '0005_car_is_parked'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='parked_car',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_car.car'),
        ),
    ]
