# Generated by Django 5.2.1 on 2025-05-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_car', '0007_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
