# Generated by Django 5.2.1 on 2025-05-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_car', '0008_vacancy_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='pic',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_car.serviceuser')),
            ],
        ),
    ]
