# Generated by Django 5.2.1 on 2025-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_car', '0009_remove_vacancy_pic_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.ImageField(null=True, upload_to='auto_car/static/images/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pic',
            field=models.ImageField(null=True, upload_to='auto_car/static/images/'),
        ),
    ]
