# Generated by Django 5.2.1 on 2025-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_car', '0010_news_pic_alter_contact_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearHitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
