# Generated by Django 5.2.1 on 2025-09-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_car', '0011_yearhitory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YearHitory',
            new_name='YearHistory',
        ),
    ]
