# Generated by Django 5.2.1 on 2025-11-27 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_car', '0015_orderservice_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default=0, max_length=255, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='job_description',
            field=models.TextField(default=0, verbose_name='Описание работ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=0, max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='pic_url',
            field=models.CharField(default='http://site.ru/photo.html', max_length=500, verbose_name='URL фото'),
        ),
    ]
